spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.163.138:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.163.138
    port: 6379

server:
  context-path: /sell
wechat:
  mpAppId: wxcee54310cc1ea263
  mpAppSecret: 0368320d1e22b690a490ea3d9914fa4b
  openAppId: wxcee54310cc1ea263
  openAppSecret: 0368320d1e22b690a490ea3d9914fa4b
  mchId: 231
  mchKey: 213
  keyPath: 213
  notifyUrl: http:/dwadxxx.com.xxx/sell/pay/notify

projectUrl:
  wechatMpAuthorize: http://fibkij.natappfree.cc
  wechatOpenAuthorize: http://fibkij.natappfree.cc
  sell: http://fibkij.natappfree.cc/sell

